### ISSUE TITLE
[1.15.2] Fruits not breaking with leaves.

### ISSUE THREAD

**Issue by curlywaffles** [MatrexsVigil/phc2trees#1]
Fruits not breaking with the leaves. Can be replicated 100%
![pamstrees001](https://user-images.githubusercontent.com/58758245/78199157-7a858d80-7450-11ea-8824-f1ffc5ba7b58.PNG)

**Comment by IchigoGames** [comment]
same

**Comment by IchigoGames** [comment]
same
![2020-04-07_12 22 58](https://user-images.githubusercontent.com/11888162/78700199-b5f9df00-78ca-11ea-9185-cfab2c3c2d8d.png)

**Comment by IchigoGames** [comment]
there is less floating fruit when you dont use fastleafdecay but still a few of them

**Comment by Linguardium** [comment]
something's up with the uploads (uploaded to wrong project) but can you check https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops/files/2958435 to be sure that it has been fixed?

**Comment by IchigoGames** [comment]
ok

**Comment by IchigoGames** [comment]
this is fixed

**Comment by curlywaffles** [comment]
Confirmed fixed.
