### ISSUE TITLE
Server crash with new recommended version of Forge

### ISSUE THREAD

**Issue by Darkfiend009** [MatrexsVigil/phc2trees#11]
Minecraft: 1.15.2
Forge: 31.2.0
Harvestcraft Trees and Crops: 1.0.4

Crash Report: https://pastebin.com/TLY6g9C9

Server crashes while trying to launch with the newest version of Forge (31.2.0).

**Comment by Linguardium** [comment]
Sorry. This was my fault, i used a client method unknowingly, fixed in #12 
sorry again

**Comment by Linguardium** [comment]
something's up with the uploads (uploaded to wrong project) but can you check https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops/files/2958435 to be sure that it has been fixed?

**Comment by IchigoGames** [comment]
thank god i was hoping for a crash so that a new version of pams2trees would get uploaded just please for the love of god do not remove 105 then re upload it as 105

**Comment by IchigoGames** [comment]
or mod will be back to broken as far as uploading modpacks go.

**Comment by IchigoGames** [comment]
darn it :( 1.05 is for pams2foodcore not trees will pams2trees get a update ?
