### ISSUE TITLE
pams2tree [1.0.5] mc [1.15.2] isnt get read correctly by the twitch app

### ISSUE THREAD

**Issue by SDUBZ** [MatrexsVigil/phc2trees#15]
the twitch app on export doesnt recognize
https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees/files/2958436

as its actually on curseforge for some reason
as seen below
 
![image](https://user-images.githubusercontent.com/14084377/82728146-fd7ce300-9d31-11ea-9f12-00146e567c59.png)

**Comment by IchigoGames** [comment]
yes this is also a issue with server files they will never get approved as long as where on version pamhc2trees-1.15.2-1.0.5.jar and all it would  take to fix both of these is for them to make a few miner changes it does not mater what and upload pamhc2trees-1.15.2-1.0.6.jar

**Comment by IchigoGames** [comment]
hack just rename pamhc2trees-1.15.2-1.0.5.jar to pamhc2trees-1.15.2-1.0.6.jar and FIXED

**Comment by IchigoGames** [comment]
wish they fixed this i cant upload my server files to curse anymore because of this.

**Comment by mr-poyo** [comment]
@IchigoGames 
I found a workaround. 

It seems if trees2 is a fresh install it works fine. Try this just before exporting your pack: downgrade 1 version of trees2, then upgrade back to 1.0.5. Immediately after, try the export. For me, it works if I do it in this order.

**Comment by IchigoGames** [comment]
ya iv actually been doing that for some time now for the modpack updates but it does Not work for server Files

**Comment by IchigoGames** [comment]
to be clear this is not the fault of twitch but who ever re uploaded the mod as the same version that was removed all that needs to be done to fix this is a new version even if no changes are made. other then changing the number at the end.

**Comment by IchigoGames** [comment]
HOW has this Not been updated yet there has to be a few bugs by now for the love of god we just need a upload with a new version number its not rocket science

**Comment by IchigoGames** [comment]
thank god there was a crash that forced them to update this. this can be closed now.
