### ISSUE TITLE
Repeated Dedicated Server Crash [1.14.4]

### ISSUE THREAD

**Issue by WalkerNewton** [MatrexsVigil/phc2trees#16]
Dedicated server will crash on startup 99/100 times due to an error during the common_setup event phase.

I'm using Minecraft version 1.14.4 - Forge 2.8.6
**Log**: https://pastebin.com/vayyVtnx

When I remove phc2crops, phc2trees, & phc2foodcore - everything works fine.

**Comment by amazingbeans** [comment]
Following this, hope to see an update! <3

**Comment by MuRkYrULEz** [comment]
Following to see if there is a fix!

**Comment by WalkerNewton** [comment]
Dropping the launcher log as the crash-report swallowed the actual issue: https://pastebin.com/9F73UFez

**Comment by WalkerNewton** [comment]
Pack will load with ALL mods in log except for phc2trees.
