### ISSUE TITLE
Crash on dedicated server and in single player forge 1.15.2 

### ISSUE THREAD

**Issue by thynightmares** [MatrexsVigil/phc2trees#21]
I was playing with a couple friends on a forge 1.15.2 server  and we were exploring different areas and suddenly the server crashed, we were able to find out it was the location one of us were in, i tried to fly around in single player to see if it happens there and it does. This is from the single player crash and is basically identical to the other, same biome and everything but i dont understand much other than that. https://pastebin.com/gKqaCF1E

**Comment by djmattyg007** [comment]
What version of the mod were you using?

**Comment by thynightmares** [comment]
these are all the mods and the versions

forge-1.15.2-31.2.0-server.jar
forge-1.15.2-31.2.0-universal.jar
pamhc2trees-1.15.2-1.0.6.jar
pamhc2foodcore-1.15.2-1.0.7.jar
pamhc2crops-1.15.2-1.0.5.jar
