### ISSUE TITLE
1.16.2 WorldGen/Registry Fixing

### ISSUE THREAD

**Issue by MatrexsVigil** [MatrexsVigil/phc2trees#22]
I need help fixing all the WorldGenRegistries and everything in the worldgen/ folder.

**Comment by thepriz** [comment]
I am more than willing to help. I don't have much experience with Minecraft modding as of yet. If you want lead me in the right direction of what to do, I can help out.

**Comment by bessiq** [comment]
You might find some good info/help in the Minecraft Worldgen Discord: https://discord.gg/BuBGds9
