### ISSUE TITLE
Upon installing PneumaticCraft: Repressurized, started crashing on load

### ISSUE THREAD

**Issue by Twisted-Code** [MatrexsVigil/phc2trees#23]
client logs:
[latest.log](https://github.com/MatrexsVigil/phc2trees/files/5215031/latest.log)
(debug log is unavailable because I'm running this via twitch and apparently that hijacks FML's logging system)
server logs:
n/a

Description:
Harvestcraft Trees threw an exception after I added PneumaticCraft: Repressurized alongside HC and the rest of [my pack](https://www.curseforge.com/minecraft/modpacks/puncher-pack-6-golden-carrot-edition).
Due to a number of factors, I want to be able to give more of a description, but honestly have no idea what's going on here. There wasn't as much information as I'm used to in the traceback so... if you'd like any further information about my installation, or just want me to go away, let me know 😛

**Comment by kairanaquazi** [comment]
Sorry for the late response, but this appears to be an issue with Cyclic and Vampirism.

**Comment by Twisted-Code** [comment]
So let me get this straight, there are at least 4 mods that are possibly involved in a critical loading exception? Great, so that on top of the fact that I am not really _actively_ maintaining this pack anymore and I imagine most of the modders involved are moving away from 1.15, means it's probably not worth trying to fix this unless it (or something similar) continues to happen in 1.16
of course, if I'm wrong and it's actually likely something really simple that I could help troubleshoot by, for instance, loading my pack and force-crashing the game with F3 + C, I'm all for it... so long as at least one other person is fairly certain it's worth the effort.

**Comment by Twisted-Code** [comment]
Like I said above, this probably isn't worth continuing to troubleshoot, and now it's been inactive for almost 4 months. closing!
