### ISSUE TITLE
Pam's HarvestCraft 2 Fruit Trees (pamhc2trees) encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by okidor** [MatrexsVigil/phc2trees#3]
Hi everyone,
i got the following error during a server restart.

https://pastebin.com/FaWXkGyc

It works after a second restart.
I also saw that this issue was already mentionned in the comments on the curse forge page of the mod.

Now the real problem is that my server is hosted on omgserv, and the server restart each night (i don't want to disable this), thus the server has a probability to crash every night, which is annoying.

The version i am using is : pamhc2trees-1.15.2-1.0.2

**Comment by IchigoGames** [comment]
Same thing happens random times loading client and server same version as above

**Comment by MatrexsVigil** [comment]
Please try doing this without Optifine and other mods except mine.  Does it still happen?  Thank you for your help.

**Comment by IchigoGames** [comment]
still a few but not as bad as before with no other mods i think pams does not work well with fastleafdecay.
![2020-04-07_14 58 55](https://user-images.githubusercontent.com/11888162/78713805-6e7e4d80-78e0-11ea-9c07-58cde954e047.png)

**Comment by IchigoGames** [comment]
well it happens on servers too and servers do not have optfine its a hard one  to test as even if we load and it does not happen it does not mean it will not happen it happens at  random on server and client heres some log files if that helps https://pastebin.com/bZ1FKXf7
[latest.log](https://github.com/MatrexsVigil/phc2trees/files/4453313/latest.log)

**Comment by okidor** [comment]
Our server crashed again this night during restart, but this time, it's Biomes' O Plenty who caused the error during the common_setup phase.

So, maybe an incompatibility between the two mods ?
@IchigoGames did you have Biomes' O Plenty when your crash happened ?

**Comment by IchigoGames** [comment]
ya

**Comment by WalkerNewton** [comment]
Hi hi, this is my crash log that I am also getting using the whole PHC2 suite of mods along with a bunch of others! - I have restarted the server countlessly to have the same mods crashing.

https://pastebin.com/XXhxJeUY

I saw this issue so decided to add on here. If you need anything else, let me know!

**Comment by mooglerae** [comment]
I have had the same error and am not using Optifine.

**Comment by HerrBeef** [comment]
I have the same error and i'm also not using optifine. The funny thing is it happens only some times for me. every 2 or 3 time the server starts fine. (Not really stable but it at least starts)

**Comment by IchigoGames** [comment]
WalkerNewton this bug report is for the 1.15.2 pams you should make a separate report for yous

**Comment by IchigoGames** [comment]
this happens with this mod xlfoods and charm each crash at random and give same crash report https://github.com/mariot7/XL-Food-Mod/issues/65

**Comment by IchigoGames** [comment]
wish this could get fixed its now one of the only mods left that still gets this crash quark just fixed there random crash on startup

**Comment by Rams59** [comment]
same happening to me with my Server. Very Annoying

**Comment by IchigoGames** [comment]
might be fixed in new version its random when it happens so not sure

**Comment by mr-poyo** [comment]
I have this mod (1.15.2) on my server and am also experiencing this startup crash. I started opening each individual crash log and they all say the same thing, "error during the common_setup event phase" but with different mods too. I decided to keep a tally of each crash:

I generally experience a server startup crash 1 out of 4 restarts. Sometimes they happen in a row.. :c

**Pam's Harvestcraft 2 Fruit Trees** - 12 crash reports
**Quark** - 2 crash reports
**Gobber 2** - 2 crash reports
**Biomes O Plenty** - 1 crash report
**Building Gadgets** - 1 crash report
**Silent Gear** - 1 crash report
**Simple Farming** - 1 crash report
**Upgrade Aquatic** - 1 crash report

It seems like, while other mods are occasionally throwing the same "error during the common_setup event phase" error, I am getting it much much more frequent with fruit trees.

**Comment by Alkiasan** [comment]
Getting the same issue too. Has always been fruit trees.
Here are the only errors relating to it:
![image](https://user-images.githubusercontent.com/62717881/88353357-123b1e80-cd55-11ea-8750-456ce278b50c.png)
![image](https://user-images.githubusercontent.com/62717881/88353362-1830ff80-cd55-11ea-8710-b302dfe146bf.png)

**Comment by Alkiasan** [comment]
Happens seemingly random, sometimes minecraft starts just fine.

**Comment by kalkafox** [comment]
I am able to reproduce this a few times, except it happens on the client for me; it has never happened on the server. I reported my findings [here.](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees?comment=66)
