### ISSUE TITLE
[1.15.2] you can walk through maple logs.

### ISSUE THREAD

**Issue by IchigoGames** [MatrexsVigil/phc2trees#4]
you can walk through maple logs 
![2020-04-07_12 19 33](https://user-images.githubusercontent.com/11888162/78699847-294f2100-78ca-11ea-8f66-797f18b68725.png)

running 
Minecraft 1.15.2
Forge 31.1.30 and 36
pamhc2trees-1.15.2-1.0.2

**Comment by Linguardium** [comment]
likely has to do with 
https://github.com/MatrexsVigil/phc2trees/blob/3f9167b321b5d8bbd1b06637de857fe5ac11c62a/src/main/java/com/pam/pamhc2trees/init/BlockRegistry.java#L231
adding the no collision property.

**Comment by IchigoGames** [comment]
can we add this bug to garden bushes it would be nice to be able to walk through them.

**Comment by Linguardium** [comment]
I have a fix i am going to PR, just looking for any other quick easy kills (and trying to get a forge dev env setup)

**Comment by Linguardium** [comment]
something's up with the uploads (uploaded to wrong project) but can you check https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops/files/2958435 to be sure that it has been fixed?

**Comment by IchigoGames** [comment]
this is fixed
