### ISSUE TITLE
(1.15.2) white_dim config entry does not let features spawn in other dimension

### ISSUE THREAD

**Issue by TelepathicGrunt** [MatrexsVigil/phc2trees#6]
Like the title says, the white_dim config entry doesn't seem to work. A full report of the issue can be found on phc2crops's issue tracker here:
https://github.com/MatrexsVigil/phc2crops/issues/5

All the info on there is the same for this mod as well and the issue is identical. Hopefully this can be fixed soon!

**Comment by IchigoGames** [comment]
had same issue pams has not updated to the new way minecraft does dim ids it still works with only numbered ids when it should be able to work with dims ids like yamda_dim

**Comment by Linguardium** [comment]
something's up with the uploads (uploaded to wrong project) but can you check https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops/files/2958435 to be sure that it works now?

**Comment by TelepathicGrunt** [comment]
I just tested 1.0.4 and the dimension works in that. It must had been fixed in that update but I'll test 1.0.5 to make sure it also work for that version as well when it's approved. :)

Though I did noticed that pams has a config in both the regular config folder and in the world's own config folder. The two configs are the same in both but it's the world's config that is used in worldgen it seems. Maybe removing the config file in the regular config folder will help prevent config confusion.

**Comment by IchigoGames** [comment]
one might be server config lots of mods have a config thats not in the config folder but is in server config  folder in world folder

**Comment by Linguardium** [comment]
> I just tested 1.0.4 and the dimension configs works in that. It must had been fixed in that update but I'll test 1.0.5 to make sure it also work for that version as well when it's approved. :)
> 
> Though I did noticed that pams has a config in both the regular config folder and in the world's own config folder. The two configs are the same in both but it's the world's config that is used in worldgen it seems. Maybe removing the config file in the regular config folder will help prevent config confusion.

yeah, the issue in 1.04 is that it crashes servers due to me miscoding something. 1.05 fixed that

**Comment by TelepathicGrunt** [comment]
@Linguardium Yep I can confirm it still works perfectly in 1.0.5. Thank you! I'll close this issue now

@IchigoGames I'm sorry but I don't really understand what you were trying to say. If a mod has a config on a per-world basis, server owners can still access and change that config no problem as no one complained about that with my mod. What seems odd is having both a regular config and a per-world config when they are the same and the game is reading only from the per-world config. That means the regular config is now useless and does nothing.  It's not game breaking or anything. Just an oddity
