### ISSUE TITLE
Config Change-feature request 1.15.2

### ISSUE THREAD

**Issue by IchigoGames** [MatrexsVigil/phc2trees#7]
Hello this is not a bug report but a request to change something in config for both 
phc2trees and phc2crops in 1.15.2 

i was trying to add the dim mod yamda to pams whitelist when i found out i could not due to yamda using resource ids and pams does not support this check link for more info edit to be clear it crashed as soon as yamda_dim the resource id was added to whitelist. 

https://github.com/Sunekaer/YAMDA/issues/34#issuecomment-617317041

Not a coder my self but it looks like for this to works pams need to change over to supporting resource ids. or what i was thinking and what i believe other mods do that are working in that dim without any changes from me like XLFood mod and Ray's Dongles both that add crops and are spawning is just to not have a whitelist only have a blacklist and spawn in any dim not on blacklist i think that would fix this issue as well.

Minecraft 1.15.2
Forge 31.1.47
pamhc2crops-1.15.2-1.0.3
pamhc2trees-1.15.2-1.0.3
YAMDA-5.0.3

**Comment by Linguardium** [comment]
something's up with the uploads (uploaded to wrong project) but can you check https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops/files/2958435 to be sure that it works now?

**Comment by IchigoGames** [comment]
i added the dim to the whitelist and loaded it before doing so i made sure it was no crashing it worked fine after changing  config to add dim it crashed https://pastebin.com/mdAJXV0Q it looked like it was something to do with cooking for block heads so i removed that mod and it still crashed https://pastebin.com/r9YDkNS3 as soon as i reset the pams config it loaded fine

**Comment by Linguardium** [comment]
this is an odd error. 
the error is showing that CFB is referencing something that doesnt exist, in this case, it is trying to access the colors of a specific block during initialization (which has nothing to do with pams...pams doesnt even touch that

It looks like CFB cant initialize colors if something silently crashes? (dank storage, rftools, and a few others were shown to cause this same issue with CFB).  I'll look into it, what dimension mod are you using and adding to the whitelist?
and did you test with just this dimension mod and pam's (and CFB since it is affected)

**Comment by Linguardium** [comment]
so, i just tested with YAMDA, CFB, and pam's trees. 
Pam's 1.0.5
Yamda 5.0.3
Forge 31.1.27 (single player)
Forge 31.2.0 (Server)
CFB 8.0.1

could not reproduce. Created world and let it load. save+quit
changed config to `white_dim = ["minecraft:overworld", "yamda:yamda_dim"]`
reloaded, no crashes.
tried both single and multiplayer, didnt crash.

I need versions and steps that reproduce this with the specific mods its having issues with. It sounds like another mod is crashing silently and indicating an issue. If you can isolate it to specific mod combos that create an issue (less than 5) then i will troubleshoot more, but at this point, it seems Pam's is working fine with both dimension mods and CFB and other Block color renderers

**Comment by IchigoGames** [comment]
oh ok i had ["minecraft:overworld", "yamda_dim"] mabey that was the issue let me check

**Comment by IchigoGames** [comment]
ok ya as soon as i put the right name in "yamda:yamda_dim the crashing stoped it loads up find but im looking around in mining world and see no pams crops or trees

**Comment by Linguardium** [comment]
If it was genned you have to go to a new area that hasnt genned yet

**Comment by IchigoGames** [comment]
it was a new world but ill try one more time.

**Comment by IchigoGames** [comment]
ya brand new world no pams

**Comment by Linguardium** [comment]
ok, i just ran 2 test.
Test1:
1 - begin new game and let the overworld generate
2 - exit and save
3 - edit the serverconfig (added the modified whitelist)
4 - load back into world and travel to yamda dimension
There were pam's trees.

Test2:
1 -  add the modified pam config to defaultconfigs folder
2 - launch Minecraft and start a new world.
3 - travel to YAMDA dimension.
There were pam trees

i feel like you may be doing something wrong. You are editing the config in the serverconfigs folder in your saves/world or world folder (depending on server/client)?

**Comment by IchigoGames** [comment]
i am changing the config in the normal config folder changed it to white_dim = ["minecraft:overworld", "yamda:yamda_dim"] then made a new world and whent into mining world

**Comment by IchigoGames** [comment]
you mean adding it to the folder defaultconfigs ? theres nothing in that one atm i changed the config it gives your in normal folder

**Comment by Linguardium** [comment]
inside the world save folder is a folder called serverconfigs
this is the folder used in 1.14+ for config files (primarily)

inside the main minecraft folder is a folder called defaultconfigs
this is the folder to put your default configs that will be copied to the new world's serverconfig folder.

the main config folder is confusing and doesnt do what you want.

**Comment by IchigoGames** [comment]
oh ok

**Comment by IchigoGames** [comment]
ya that worked thank sorry about the confusion
